"""empty message

Revision ID: 24b78d807d50
Revises: e50f3d678b67
Create Date: 2019-12-17 10:38:11.866085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24b78d807d50'
down_revision = 'e50f3d678b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_ibfk_1', 'message', type_='foreignkey')
    op.drop_column('message', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('message_ibfk_1', 'message', 'user', ['uid'], ['id'])
    # ### end Alembic commands ###
