"""empty message

Revision ID: 8cce4abd321b
Revises: 7abd939d895a
Create Date: 2019-12-18 10:28:30.815494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cce4abd321b'
down_revision = '7abd939d895a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('comment', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'comment')
    # ### end Alembic commands ###
